Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
  
	config.vm.define "mradwanS" do |server|
	  server.vm.hostname = "mradwanS"
	  server.vm.network "private_network", ip: "192.168.56.110"# echo "192.168.56.110 test.local" | sudo tee -a /etc/hosts
	  server.vm.network "forwarded_port", guest: 80, host: 80
	  server.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
		v.name = "mradwanS"
	  end
	  server.vm.provision "shell", path: "scripts/run.sh"
	end
end