# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian12"
    config.vm.box_version = "4.3.12"

    # SSH
    config.ssh.insert_key = true
    config.vm.synced_folder "./shared", "/shared"

    $ssh_setup_script = <<-SCRIPT
      mkdir -p /home/vagrant/.ssh
      chmod 700 /home/vagrant/.ssh
      cat /shared/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SCRIPT
    
    config.vm.define "bammarS" do |server|
      server.vm.hostname = "bammarS"
      server.vm.network "private_network", ip: "192.168.56.110"
      
      # https://docs.k3s.io/installation/requirements?os=debian#hardware
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end

      server.vm.provision "shell", inline: $ssh_setup_script
      server.vm.provision "shell", inline: <<-SCRIPT
        sudo apt install iptables -y
        sudo iptables -F
        curl -sfL https://get.k3s.io |  sh -
        sudo cat /var/lib/rancher/k3s/server/node-token > /shared/node-token
      SCRIPT
    end
    
    config.vm.define "bammarSW" do |worker|
      worker.vm.hostname = "bammarSW"
      worker.vm.network "private_network", ip: "192.168.56.111"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
      end
      worker.vm.provision "shell", inline: $ssh_setup_script
      worker.vm.provision "shell", inline: <<-SCRIPT
        sudo apt install iptables -y
        sudo iptables -F
        curl -sfL https://get.k3s.io | K3S_TOKEN=$(cat /shared/node-token) K3S_URL=https://192.168.56.110:6443 sh -
      SCRIPT
    end
  end
