# -*- mode: ruby -*-
# vi: set ft=ruby :

system("mkdir -p ./confs/.ssh")
if File.exist?(ENV["HOME"] + "/.ssh/id_rsa.pub") == false
  puts "SSH key not found"
  puts "Generating SSH key"
  system("ssh-keygen -t rsa -b 4096 -q -P '' -f " + ENV["HOME"] + "/.ssh/id_rsa")
end

File.open(ENV["HOME"] + "/.ssh/id_rsa.pub", "r") do |f|
  SSH_KEY = f.read
end

File.open("./confs/.ssh/id_rsa.pub", "w") do |f|
  f.write(SSH_KEY)
end

Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian12"
    config.vm.box_version = "4.3.12"

    # SSH
    config.ssh.insert_key = true
    config.vm.synced_folder "./confs", "/confs"

    $ssh_setup_script = <<-SCRIPT
      mkdir -p /home/vagrant/.ssh
      chmod 700 /home/vagrant/.ssh
      cat /confs/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SCRIPT
    
    config.vm.define "bammarS" do |server|
      server.vm.hostname = "bammarS"
      server.vm.network "private_network", ip: "192.168.56.110"
      
      # https://docs.k3s.io/installation/requirements?os=debian#hardware
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end

      server.vm.provision "shell", inline: $ssh_setup_script
      server.vm.provision "shell", inline: <<-SCRIPT
        sudo apt install iptables -y
        sudo iptables -F
        curl -sfL https://get.k3s.io |  sh -
        sudo cat /var/lib/rancher/k3s/server/node-token > /confs/node-token
      SCRIPT
    end
    
    config.vm.define "bammarSW" do |worker|
      worker.vm.hostname = "bammarSW"
      worker.vm.network "private_network", ip: "192.168.56.111"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
      end
      worker.vm.provision "shell", inline: $ssh_setup_script
      worker.vm.provision "shell", inline: <<-SCRIPT
        sudo apt install iptables -y
        sudo iptables -F
        curl -sfL https://get.k3s.io | K3S_TOKEN=$(cat /confs/node-token) K3S_URL=https://192.168.56.110:6443 sh -
      SCRIPT
    end
  end
